CREATE DATABASE secu;
CREATE USER secu IDENTIFIED BY 'MYSQL_SECU_PASSWORD';
GRANT USAGE ON *.* TO 'secu'@'%' IDENTIFIED BY 'MYSQL_SECU_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON `secu`.* TO secu;
FLUSH PRIVILEGES;